### ISSUE TITLE
Can't build with libxml 2.10.3

### ISSUE THREAD

**Issue by damienthivolle** [xml4r/libxml-ruby#195]
Hello,

I can't install the gem on Mac OS 13.1 with libxml 2.10.3, because xmlXPtrNewRangeNodes and xmlGetFeaturesList have been deprecated.

```Undefined symbols for architecture arm64:
  "_xmlGetFeaturesList", referenced from:
      _rxml_features in ruby_xml.o
  "_xmlXPtrNewRangeNodes", referenced from:
      _rxml_xpointer_range in ruby_xml_xpointer.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [libxml_ruby.bundle] Error 1
```

Running ruby 3.1.3p185.

Is support for newer versions of Gnome libxml2 planned?

Thanks!

**Comment by cfis** [comment]
Thanks for the report. Yes, happy to support latest version. Or happy to take a PR too.

**Comment by cfis** [comment]
Took a look - library builds fine for me with libxml 2.10.3 on Linux and Windows. That is on x86_64, maybe Arm is different?

I do see the _xmlXPtrNewRangeNodes deprecation but not the _xmlGetFeaturesList one. Will see what is required to update those.

**Comment by cfis** [comment]
I think this has been fixed?
